sudo: false
language: go
go:
  - master
services:
  - docker
script:
  - make docker/build
env:
  global:
  - secure: S59LmqulUZhvDIDg4PofGQaTNI66O5SFGeSTFu4h8TggJnOq23Po+uXqVM4+KsOdNSk8G8ysy3I02bXu+arZAEbbwEHWy4ZeSvwdkfU/JLuFF3KyCmSnPHR0GL/aiO/za5NV75ms1nnIV2j0TS3tgVPOP71o6rAMHLyPYTGCXJGXjbmRmLVJ3hi8fs/8WnfmaRR7WuYFkxX4Ofys3NUeynlrZ+bPJQVZpa8M3mzQDqc+HkEO6hfNWU+uWzP1eTRmfliMF9LTX8QmBphxzEXrKmaRLJbQWDxjv+btm3AMYP0kjcUZymhovxSyJ5XXFNcKySVlbi6MIlkLcChUxpnXTLGCQe4m0cZMRthP6KGR37jWF2VEfqRhwI1VvEjU+cJt3f9vPuFtTLkNbnDw5pfxBPxTvLGmF8aU4hsMAV0X2L1mMtl8V5UqdLObFB3crxyFMSIHdljOQCEOjh5DjylgcqFehF/8ZREIU8rp/G4zc7+47yXeqeQa4118yJ++x9efUWAHS2RwCCNFm+oe+26057+IHsKXr6xhFnVwPs5u+8jPGueufUd3mfsp4TJhklSMBknuDynQIO5zWQ+sv17Yf4/JUS9dsOB8vDJZFmXenVFdflHWL1xc8jF3iQbgiOgoOEHstngNHSpAvM1fXOMWPCB/+0kEUvwfJeUq2yMPO3Y=
  - secure: DO0Jfat+Xps+wuS3XLuv5oh6gn7IoKXdUsdJRxFzfSJChrB2dggWHrSweaY9X/EP6ivxz8PPFDqM8NJQEMH/UDYY7dPvC6D4vSN/eYcF+27TYcOkXs6Ln/PciHt7aN71IgZGAzu3vVWdlEWqnQ83+UEPBBN6nUrjSdi5zNrtAjVp/wOOkIsIea/pH37ypmt5w4oD+/HI54YjHxYm9oth7U0eoXDvfLjCpghzF4M6cmmZ9B8NS9grAVW+gg5w8NLneYVOSaXXwPF1UtQSU+520SMc+2+QJv9PDLLy+qynOmL0nAVlhaM4z/MrcptP7UYOXFSnLQy+ERn6S/qDhKyC9gytdriZRkp8IC8INiVzHmZ2D73LWdt8sxGH3HR1rT2IT+QpOqmifsChVRIOJG0V8LwYq5csA6+HDNR4qX/DVjzaktEvDADQJ4TJAArRwGv3koS3hEsGZkmrH9YZFL6XVvMaKWoN4irI4P8QyRcTMG/OFJ3b7rQWGDO2FAQfsYy7uxAHJ2VdJAPvQyDjjU04RlhKqYJjftY6/YfERo/89yrFOpCXn4dxB5mfj5hErVs42VXy8uvkgKOKhUk3ucTnIJJ9Y4JQSW4Vk8v+/pH5DdYMRH14RRyuSj4mFp8ZLkvlY+amczivtxhRQi34LT3ap3jZ8MixTfd7xiiTLuqEC7I=
